### ISSUE TITLE
The One Probe 1.2.1 cause new issues

### ISSUE THREAD

**Issue by mcdodge34** [DrManganese/TOPAddons#10]
I hate to bring more work to you, but again, MCJTY is on fire and created a new version of his awesome The One Probe, this time it seems that with TOP addons, we can't see content of chests, crates, furnaces, machines, crushers or anything while sneaking which was a very practical thing, I've done tests and without TOP addons, it works as intended like last time, I noticed we can still see the content of storage drawers and it works #1 so this part is still in good shape.

**Comment by DrManganese** [comment]
Wow I should just change my name to DrSloppy, fix right away with v0.9.0!

**Comment by DrManganese** [comment]
Well I tested it myself now and I can always see the the contents when sneaking, I used a pack with TOP v1.2.1 and TOP Addons 0.8.0. Could you go over some steps I might have missed to encounter the bug?

**Comment by mcdodge34** [comment]
I'll try to do some tests later, I have medical appointments today so I'll be back later for sure, could it be latest forge ???, I would also reset my configs, perhaps something changed.

**Comment by mcdodge34** [comment]
Doing some testings right now, it worked well for a few seconds after loading my world then suddenly, I can't see the chests or any inventory content anymore, I did reset both config files to see if this would solve the issue, it didn't do anything, not sure if a log would help you somewhere, if you figure out where to look for a log of what happens, I could provide something to help you. I've got basically the content of Hermitpack plus a bunch of mods they don't have, I load 98 mods on my pack right now.
