### ISSUE TITLE
Use new TOP API features

### ISSUE THREAD

**Issue by DrManganese** [DrManganese/TOPAddons#100]
Investigate and implement API features added by @Speiger.

**Comment by Speiger** [comment]
If you have improvement suggestions go ahead xD

I think progressstyle-color/borderless color with 2 arguments needs a tiny change to be better

**Comment by DrManganese** [comment]
I'm very happy with the constructors and helper method of the styles. Makes the builder chains less massive.
The centered progress bar is a great addition, I was able to get rid of the one I implemented myself.
Another nice feature to have would be a simple way to fully override the progress bar text, so you could show e.g. "Ready" when the bar is at 100%;

**Comment by Speiger** [comment]
Eh isn't that what "numberformat.none" is for? We override the entire progressbar text by just using a prefix + numberformat none.
It looks like a hack but it isn't. Its actually quite the elegant solution.
Thats why this constructor exists in the first place:
https://github.com/McJtyMods/TheOneProbe/blob/1.16/src/main/java/mcjty/theoneprobe/api/IProgressStyle.java#L20

**Comment by DrManganese** [comment]
Doh, didn't see that one. Indeed that would do it.

**Comment by Speiger** [comment]
@DrManganese you now need to use the Implementation to access the helper functions because Mjdty just got rid of the static constructors. Good luck.
