### ISSUE TITLE
Crash with the new version of Thermal Series mod

### ISSUE THREAD

**Issue by magcicada** [DrManganese/TOPAddons#106]
Crash with the new version of Thermal Series mod
topaddons-1.16.5-2.1.5-beta
thermal_cultivation-1.16.5-1.4.0.2
thermal_expansion-1.16.5-1.4.0.1
thermal_foundation-1.16.5-1.4.0.4
thermal_innovation-1.16.5-1.4.0.1
thermal_locomotion-1.16.5-1.4.0.1

CR:
	`Caused by 0: java.lang.NoClassDefFoundError: cofh/thermal/lib/tileentity/ThermalTileBase`
		`at io.github.drmanganese.topaddons.addons.thermal.ThermalExpansionAddon.<clinit>(ThermalExpansionAddon.java:28) ~[topaddons:1.16.5-2.1.5-beta] {re:classloading}`
		`at io.github.drmanganese.topaddons.AddonRegistry.registerAddon(AddonRegistry.java:33) ~[topaddons:1.16.5-2.1.5-beta] {re:classloading}`
		`at io.github.drmanganese.topaddons.AddonRegistry.registerAddon(AddonRegistry.java:55) ~[topaddons:1.16.5-2.1.5-beta] {re:classloading}`
		`at io.github.drmanganese.topaddons.TopAddons.registerAddons(TopAddons.java:61) ~[topaddons:1.16.5-2.1.5-beta] {re:classloading}`
		`at io.github.drmanganese.topaddons.TopAddons.<init>(TopAddons.java:48) ~[topaddons:1.16.5-2.1.5-beta] {re:classloading}`
		`at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}`
		`at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}`
		`at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}`
		`at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?] {}`
		`at java.lang.Class.newInstance(Class.java:584) ~[?:?] {}`
		`at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}`
		`at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}`
		`at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}`
		`at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}`
		`at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}`
		`at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}`
		`at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {re:computing_frames}`
		`at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {re:computing_frames}`
		`at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}`

**Comment by notFalkon** [comment]
also happens to me

**Comment by DrManganese** [comment]
Thanks for the report. I'll have a look at this.

**Comment by KingLemming** [comment]
Apologies for any internal changes I made that required this.

**Comment by DrManganese** [comment]
v1.16.5-2.2.0-beta uploaded to CurseForge and should be available soon. Please re-open if your issue persists.

@KingLemming no problem. This kind of work is expected with TOP Addons' implementation 🙂.
