### ISSUE TITLE
Probe Helmet Crash w/ Neotech

### ISSUE THREAD

**Issue by WenXin20** [DrManganese/TOPAddons#11]
TOP Addon v0.9.0
NeoTech v3.3.0
Forge 2116
The game froze when the probe was combined with the Neotech helmet.
[Log](http://pastebin.com/Nvt3PeEe)

**Comment by DrManganese** [comment]
Thanks for the report, will investigate asap.
(if this happened on a server you can do ```/tophelmet blacklist add``` while holding the helmet to prevent future crashes)

**Comment by WenXin20** [comment]
Ok, thanks, it was single player thought

**Comment by DrManganese** [comment]
It seems like I'll have to disable crafting the probe with the electrical helmet. The crash is caused by Neotech and I can't add it as an upgrade in the soldering machine.

**Comment by WenXin20** [comment]
Ok, that's fine.
