### ISSUE TITLE
Hotkeys to open JEI/derivatives

### ISSUE THREAD

**Issue by Xetaxheb** [DrManganese/TOPAddons#113]
**Describe for which mod, block or entity you'd like to see TOP information**
JEI/HEI/etc integration

**Describe the solution you'd like**
Pressing bindable keys while looking at a block/entity to open its recipe/usage view

**Comment by DrManganese** [comment]
Thanks for the idea. This is not something I see in TOP Addons.
JEI and derivates, or some specific addon mod would be more suited to implement this feature.
