### ISSUE TITLE
Crash during startup while TOP Addons registers Thermal Expansion

### ISSUE THREAD

**Issue by DeimosJ** [DrManganese/TOPAddons#114]
Describe the bug
Crash during startup while TOP Addons registers Thermal Expansion

To Reproduce
Install TOP Addons (and The One Probe)
Install Thermal Expansion (and dependencies)
Run client or server

Expected behavior
Expect the server/game to start up and run.

Mod environment (please complete the following information):
details in crash log link

Additional context
https://pste.ch/uxaloquwas.rb

**Comment by DrManganese** [comment]
Thanks for your report, and apologies for the delay. Fixed version available on CurseForge: 
topaddons-1.18.2-2.3.1-beta.

Please reopen in case you still encounter the error.
