### ISSUE TITLE
The game crashes when trying to run TOP Addons with Thermal Series mods.

### ISSUE THREAD

**Issue by dldev32** [DrManganese/TOPAddons#115]
**Describe the bug**
When starting the game with TOP Addons and Thermal Series mods, the game crashes.

**To Reproduce**
1. Start the game with TOP Addons and Thermal Series mods.

**Expected behavior**
The problem occurs on both the client and the server.

**Mod environment (please complete the following information):**
 - Minecraft version: 1.18.2
 - Forge version: 40.2.1
 - The One Probe version: 5.1.2
 - TOP Addons version: 2.3.0-beta

**Additional context**
Crash report: [crash-2023-02-23_14.09.33-fml.txt](https://github.com/DrManganese/TOPAddons/files/10811048/crash-2023-02-23_14.09.33-fml.txt)

**Comment by DrManganese** [comment]
Thanks for the report. Same root cause as #114, working on the fix right now.

**Comment by DrManganese** [comment]
Fixed version available on CurseForge: topaddons-1.18.2-2.3.1-beta.

Please reopen in case you still encounter the error.
