### ISSUE TITLE
Blood Magic Mimic blocks don't report properly in The One Probe

### ISSUE THREAD

**Issue by kayila** [DrManganese/TOPAddons#12]
Originally I filed this for the BM devs, but was told to come here instead.  Original bug:
https://github.com/WayofTime/BloodMagic/issues/971

#### Issue Description:
There is a compatability bug between Mimic Blocks and The One Probe. We recently switched from using Waila to The One Probe and in doing so noticed that mimic blocks that were disguised would show up as whatever block they were disguised as to Waila, but as `Mimic Block` to The One Probe.

#### What happens:
Mimic blocks with stone applied show up as `Stone` to Waila, but `Mimic Block` to the one probe

#### What you expected to happen:
The one probe reports that the block is the block it is disguised as

#### Steps to reproduce:

1. Create some etherial mimic blocks
2. Place them in the world
3. Apply stone to them
4. Pull out `the one probe` or wear a helmet with it attached
5. Look at the Stone, notice the 'correct, but incorrect' block being displayed

____
#### Affected Versions (Do *not* use "latest"):

- TOPAddons: `1.10.2-0.7.0`
- BloodMagic: `1.9.4-2.1.0-65`
- The One Probe: `1.10-1.1.6`
- Minecraft: `1.10.2`
- Forge: `1.10.2-12.18.2.2123`

**Comment by DrManganese** [comment]
The One Probe uses the block's pickBlock() method to determine what to show, this is why it's showing the Mimic block. Sadly this information cannot be modified after the probe fetches it from what the client is looking at, the same happens when looking at crops.

I asked McJty about modifying this information already, but he said this is the way he intends it to work. So I can't 'fix" this unfortunately.

**Comment by DrManganese** [comment]
A recent API update from The One Probe allows me to show the mimicked block. I'll make it work asap.

**Comment by DrManganese** [comment]
Ok it's working, just wanted to know if you think it would be a good idea to tell the user they're looking at a mimic block when holding a seer sigil. [https://webmshare.com/play/Avq1w](https://webmshare.com/play/Avq1w)
