### ISSUE TITLE
Blood Altar crafting reported incorrectly when holding seer sigil

### ISSUE THREAD

**Issue by tali713** [DrManganese/TOPAddons#17]
Just a matter of scale, everything looks fine until you try to craft more than one item at a time.  At that point you can easily find yourself looking at 10,000/1,000 which would be but a minor inconvenience if it weren't for the progress bar breaking far beyond the edge of the TOP info box.

To replicate have a seer sigil, and place a hopper facing into the altar, fill the altar and drop 10 stone into the hopper, wait and laugh.

Fixed in: #16

**Comment by DrManganese** [comment]
That'll teach me to do more tests int he future :P. Thank you for the report and fix!
