### ISSUE TITLE
Adding/removing energy efficiency upgrades to Mekanism machines causes power-fill bar to extend past TOP

### ISSUE THREAD

**Issue by JaSpr** [DrManganese/TOPAddons#19]
A story in pictures: http://imgur.com/a/VTd7t

TOP seems to rely on the efficiency multiplier incorrectly.  Each time an efficiency upgrade is removed from the machine, TOP appears to properly adjust the "total available" energy that the machine can hold, but doesn't update the total actual energy that the item is holding.

The energy bar can thus extend all the way across the screen.

**Comment by DrManganese** [comment]
The RF bar is added by TOP itself, not by TOP Addons. I suggest posting the same issue on their repository (https://github.com/McJty/TheOneProbe/issues). If it doesn't get fixed I could add something myself but it seems to be easy enough to fix.
