### ISSUE TITLE
Client forced out of world with TOPAddons and Endertanks interaction

### ISSUE THREAD

**Issue by utoc** [DrManganese/TOPAddons#2]
Versions:

FML 2046
TOPAddons-1.10.2-0.4.0
endertanks-1.10.0-1.4.1
shetiphiancore-1.10.0-3.3.0 (required for endertanks)
in Minecraft 1.10.2

Log here: http://pastebin.com/aqBgTF4f

Simply place down an endertank down, your client will immedately look at it and leave the world in both single and multiplayer.  You can no longer enter that world without getting immediately kicked out.

Removing TOPAddons.jar makes the issue go away

Let me know if you need any more information :)

**Comment by DrManganese** [comment]
Seems like they're doing something strange with capabilities, but I see they have their own TOP integration anyway so I'll disable it for Ender Tanks.

**Comment by utoc** [comment]
I have a simple question if you dont mind: Is this intended to be a client/server mod or client-side only?

**Comment by DrManganese** [comment]
It's an addon to The One Probe wich is client/server so this one is aswell.
