### ISSUE TITLE
Support Request: Hatchery

### ISSUE THREAD

**Issue by mallrat208** [DrManganese/TOPAddons#26]
Hatchery is commonly used in most cases where Chickens itself is. Being able to look at the nesting pen or nest and being able to tell what the enclosed chicken or egg is would be extremely useful.

**Comment by DrManganese** [comment]
Oh I thought the hatchery was a block in the Chickens mod xD. Didn't realise it's a seperate mod. Will look into it asap. Thanks for the suggestion(s)!

**Comment by DrManganese** [comment]
https://webmshare.com/play/xAXm6
^Like this?

**Comment by mallrat208** [comment]
That's great
