### ISSUE TITLE
Chisel and ArchitectureCraft

### ISSUE THREAD

**Issue by MeinKraft** [DrManganese/TOPAddons#27]
Hello,

Could you please add support for the Chisel Factory Blocks and the ArchitectureCraft blocks.  Chisel Factory blocks just show up as Factory Block instead of Circuit, Metal Box, Fan etc

Similar problem with ArchitectureCraft

Thank you for continually updating the TOP descriptions, awesome work.

**Comment by DrManganese** [comment]
Hi,

Is adding the variant below the block like this okay?
![https://i.imgur.com/pz3fx0H.png](https://i.imgur.com/pz3fx0H.png)

Still working on architecturecraft.

**Comment by DrManganese** [comment]
Alright for ArchitectureCraft blocks the block name will be the name of the shape. The block material used is visible when sneaking.

![https://i.imgur.com/Lb23zSt.png](https://i.imgur.com/Lb23zSt.png)

Let me know if you approve.

**Comment by MeinKraft** [comment]
I think the Chisel description should be the same as the ArchitectureCraft one. As in The Shape name, then the Mod name then the Material name

if possible,  but looking great

**Comment by MeinKraft** [comment]
**Thank you** for the update.
