### ISSUE TITLE
Issue #22 patch not applied to the 1.11.2 version of the mod

### ISSUE THREAD

**Issue by VampireValik** [DrManganese/TOPAddons#28]
With topaddons-1.11.2-0.11.0 I'm experiencing the issue described in #21 and #10 where sneak viewing Storage Drawers breaks sneak viewing for other inventories. It looks like #22 contains a fix for it but it appears that fix wasn't ported to the 1.11 branch so 1.11.2 versions of the mod still have the bug.

**Comment by DrManganese** [comment]
Thanks for letting me know! Fixed jar asap.
