### ISSUE TITLE
Vanilla Animal Breeding Cooldown

### ISSUE THREAD

**Issue by MeinKraft** [DrManganese/TOPAddons#29]
Is it possible to show the cooldown from feeding animals before they can reproduce again? and maybe show the time needed for a baby to grow up?

ps. the Ender Portal shows up as 'tile.null.name'. Maybe change to 'Ender Portal', if possible

Thank You again for the Chisel and ArchitectureCraft update.

**Comment by DrManganese** [comment]
![2017-05-23 21_02_21-minecraft 1 10 2](https://cloud.githubusercontent.com/assets/1509051/26371535/53c11278-3ffb-11e7-922b-425d01beeebc.png)![2017-05-23_20 45 26](https://cloud.githubusercontent.com/assets/1509051/26371536/53cf5248-3ffb-11e7-95f7-8f990cee7271.png)
The info on the animals only shows up when sneaking or when you're holding the correct breeding item.
Let me know what you think!

![2017-05-23 20_46_02-minecraft 1 10 2](https://cloud.githubusercontent.com/assets/1509051/26371534/53b4501a-3ffb-11e7-869d-4f9342964cb2.png)

**Comment by MeinKraft** [comment]
Truly amazing. Love It. Thank You.

**Comment by DrManganese** [comment]
Added in v1.10.2-0.14.1
