### ISSUE TITLE
Hatchery: Nesting Pen reporting "Error: topaddons:hatchery"

### ISSUE THREAD

**Issue by mallrat208** [DrManganese/TOPAddons#30]
Forge: 12.18.3.2297
TheOneProbe:  1.1X-1.4.7
CompatLayer: 1.10-0.2.8
TOPAddons: 1.10.2-0.13.0

Currently when looking at Hatchery Nesting Pens the Probe is reporting an error.

I compiled a local copy of TOPAddon's that was built against the current version of TOP, _mcjty.theoneprobe:TheOneProbe:1.1x-1.4.7-57_ , and did not run into this problem.

**Comment by DrManganese** [comment]
Huh, I did the same thing, tested a new build with no changes and it no longer errors. 
Try with this [https://github.com/DrManganese/TOPAddons/releases/tag/v1.11.2-0.13.1](this build) if you have the time. It didn't error in the Twitch launcher.

**Comment by mallrat208** [comment]
So trying out that build and it worked fine for Hatchery
