### ISSUE TITLE
[1.10.2-0.12.0] - Storage drawer TOP addon assumes all stacks are 64.

### ISSUE THREAD

**Issue by JaSpr** [DrManganese/TOPAddons#31]
# Issue
When looking at a storage drawer and crouching, TOP will report the number of stack times the stacksize, but the stack size is listed as 64 for items with a stack of 16 (e.g. eggs and snowballs). This leads the player to believe they have more available space for a drawer that is already full. 

For example, in the attached [screenshot](http://i.imgur.com/TJXyS9h.png), I have a drawer that can hold 104 stacks, but I've put snowballs in one of the drawers.  Realistically, the drawer can hold 104 * 16 snowballs (1,664 snowballs) because the stack size is 16.  TOP Addons reports instead that I have 26 stacks of snowballs (which is 1,665 stacks divided by a stack size of 64).  This would make me think I had 78 stacks of storage space left.

# Suggested Solution

When doing the math for how many stacks are currently in the drawer, TOP Addon might actually create an empty stack of items (e.g. eggs) to see what its max size is, then use that number for its calculations.

# VERSIONS

Pack: FTB Beyond 1.6.1
MC: 1.10.2

TOP Addons: 1.10.2-0.12.0
The One Probe: 1.1x-1.4.6
Storage Drawers: 1.10.2-3.7.3

**Comment by DrManganese** [comment]
Will fix this asap. Thx for the report.

**Comment by DrManganese** [comment]
Fixed in v1.10.2-0.14.1
