### ISSUE TITLE
Seer's sigil is treated as divination sigil when in a sigil of holding

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [DrManganese/TOPAddons#32]
When using a Seer's sigil in a sigil of holding, you will get the altar tier but not the progress of the current craft in TOP

Noticed in version 1.10.2-0.9.1c and confirmed still an issue in 1.10.2-0.13.0, on minecraft version 1.10.2 in a modified version of FTB beyond

With seer's sigil in sigil of holding:
![2017-06-01_10 35 24](https://cloud.githubusercontent.com/assets/21071450/26671930/874956ba-46b7-11e7-9f47-57ea8f8aee66.png)

With Seer's sigil in hand
![2017-06-01_10 35 33](https://cloud.githubusercontent.com/assets/21071450/26671970/adc3b290-46b7-11e7-85a1-6bb9375e1a09.png)

**Comment by DrManganese** [comment]
Will be fixed in 0.14.1. Thanks for reporting.

**Comment by A-UNDERSCORE-D** [comment]
Thats great, thank you
