### ISSUE TITLE
Client disconnect caused by Smeltery Controller

### ISSUE THREAD

**Issue by TheVeyra** [DrManganese/TOPAddons#33]
Looking at a smeltery controller will cause the client to disconnect from the server.

More info here https://github.com/McJty/TheOneProbe/issues/168

**Comment by TheVeyra** [comment]
More info here /McJty/TheOneProbe#168

**Comment by TheVeyra** [comment]
More info here https://github.com/McJty/TheOneProbe/issues/168

**Comment by DrManganese** [comment]
Hi, what version of TOPAddons it the server running?

**Comment by TheVeyra** [comment]
0.13.0, the version shipped with FTB Beyond

**Comment by DrManganese** [comment]
Is it possible that you have some mods disabled on the server-side? That is the only way I've been able to reproduce this so far.

**Comment by TheVeyra** [comment]
Yes, we have Foamfix, FTBLib, FTBUtilities, Funky-locomotion, Journeymap, Morpheus, RFTools Dimensions, and YABBA disabled. (All versions are those shipped in FTB Beyond 1.8.1)

Might also be worth mentioning we are using Sponge.

**Comment by DrManganese** [comment]
Alright thanks for helping me figure this out. Turns out that disabling a mod that adds custom stuff to TOP on one side only messes stuff up. Will fix this asap.
In the meantime the players on your server can disable the same mods on their client and the issue should go away. (At least rftoolsdim)

**Comment by DrManganese** [comment]
I've tested f5dcd29 on a local server extensively and it should do the trick for mods I support with this mod. Release should be up soon, I hope Beyond updates pretty regularly.
