### ISSUE TITLE
Sneak hides Drawers inventory

### ISSUE THREAD

**Issue by ouroborus** [DrManganese/TOPAddons#36]
Other items show extended info when sneaking. Drawers show no inventory info when sneaking.

Minecraft v1.12.1
All The Mods 3 v3.01
The One Probe v1.12-1.4.18
TOP Addons v1.12-0.15.1

**Comment by DrManganese** [comment]
If your server/single player has the *needsProbe* setting on **Extended** the extended drawer information only shows up when you have a probe, this currently also makes the default info disappear. 

Please try sneak-looking at a drawer again while holding a probe or with the setting on **Not needed**.

You can change the setting with the `/topneed` command or by right-clicking the note you get at the start.

**Comment by ouroborus** [comment]
Thank you, I hadn't realized that config was server-side and was more nuanced than on/off.

**Comment by ouroborus** [comment]
The "Not needed" and "Extended" settings appear to operate the same, both requiring the probe to see extended information.

**Comment by DrManganese** [comment]
Normal behavior is that not needed shows everything, with and without probe equipped. If some kind of client/server mishap is happening that must be on The One Probe's side, but I'll test this case out more with a server.

**Comment by ouroborus** [comment]
As near as I can tell, `/topneed` only effects the client (or single-player). The server config, of course, affects the server. The server config limits the client setting. This seems all normal unless you happen to be op and expect command line stuff to effect the server via the client. In retrospect, the fact that `/topneed` pops up a gui, rather than directly controlling the setting, is an indicator that it may be only effecting the client.

**Comment by ouroborus** [comment]
Given the topic for this issue and the fix you provided, I'm closing this issue. I think `/topneed` works as intended, but can be slightly confusing if you make certain assumptions due to circumstances.
