### ISSUE TITLE
[1.12.2] Strange crash maybe related to TOP Addons

### ISSUE THREAD

**Issue by twoworlds** [DrManganese/TOPAddons#37]
I experience client crashes while playing on my 1.12.2 server.

The client disconnects but doesn't close. I have found this in the logfile:

https://pastebin.com/ugcjZjRq

I reported to TOP, but McJty said it was related to TOP Addons.

mc 1.12.2
TOP 2.4.18
TOP Addons 1.1.1
Forge 14.23.0.2512

**Comment by DrManganese** [comment]
Thanks for the the bug report. Will fix asap!

**Comment by DrManganese** [comment]
Trying to pin down the cause of the crash. Does it happen when you try to open the recipebook?

**Comment by twoworlds** [comment]
No, it happend while walking around. I logged in with another user and went to the same spot. It seems to be related to modular routers blocks:

https://minecraft.curseforge.com/projects/modular-routers

These are built in the floor and when looking at them, I get the crash. Without TOP Addons it shows the Info of the modular router with the installed extensions.

**Comment by DrManganese** [comment]
Oh I see. Is it possible that the server doesn't have TOPAddons installed? Or that there are some mods that have been disabled on the server but not on the client? I've had similar reports where TOP tries to add the wrong element to the HUD because of server/client mod mismatch.

**Comment by twoworlds** [comment]
You are right, TOP Addon was not installed on the server. I removed it, to resolve another crash that occured after i logged on to the server (with TOP Addon installed). The user had the recipe book open and was instantly disconnected from the server after joining. I removed TOP Addons and TOP from the server and client and was able to connect the user and close the recipe book. I activated TOP and TOP addons on the client but only TOP on the server.

This is the error on the client when he got disconnected:
https://pastebin.com/C0zhDR7X

**Comment by DrManganese** [comment]
Yep I discovered the recipe book one earlier while looking at your first report and a fix is ready.

I can't fix the dc that happens with the mod mismatch, it's linked to how TOP handles custom elements.

**Comment by power-spike** [comment]
Greetings I just had this crash as well. 

Playing on a server (pack is Powercraft!) 

Opened the Recipe Book, and crashed to desktop, part of the log:-

Caused by: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: io.github.drmanganese.topaddons.helmets.ProbedHelmetCrafting@76761ca0 Name: topaddons:probe_helmet

**Comment by DrManganese** [comment]
I forgot to publish the fix for that. Will upload when I'm at a PC.
