### ISSUE TITLE
[1.12.2] Error when looking at Oak Trees

### ISSUE THREAD

**Issue by Aiidoneus** [DrManganese/TOPAddons#38]
https://i.imgur.com/NtTkzNu.png
This is the tooltip error I get. Happens with the wood too. This probably happens with other items as well. TOP updated today so this could be the reason. 

Versions:
Forge: 14.23.0.2528
TOP: 1.12-1.4.19
TOP Addons: 1.12.2-1.1.2

If you require any additional info, Let me know.

**Comment by DrManganese** [comment]
Probably related to a recent Forestry update, are you using 1.12.2-5.7.0.204 or higher?

**Comment by Aiidoneus** [comment]
Forestry Version: 1.12.2-5.7.0.209
Currently is the version I am using

**Comment by Aiidoneus** [comment]
Verified this is fixed with topaddons-1.12.2-1.1.3.jar
Thank you for your fast fix!
