### ISSUE TITLE
[1.12.2] Compatibility w/ Binnie's Mods

### ISSUE THREAD

**Issue by SnowShock35** [DrManganese/TOPAddons#39]
#### Issue Specification

- Minecraft 1.12.2
- Minecraft Forge 14.23.2542
- Forestry 1.12.2-5.7.0.212
- Binnie's Mods 1.12.2-5.0.96
- The One Probe 1.12-1.4.19
- TOP Addons 1.12.2-1.1.3

#### Issue Description

Hi there,

Just letting you know that Binnie's mod acts weird with TOP addons. I reported it to the Binnie's Mod repository [here](/ForestryMC/Binnie/#343).

#### Issue Media

With TOP Addons
![Issue Media #1](https://ss.blamesnow.co.uk/2017/11/1510686020-1606de7d.png)

Without TOP Addons
![Issue Media #2](https://ss.blamesnow.co.uk/2017/11/1510686126-4ab40d63.png)

**Comment by DrManganese** [comment]
Caused by Binnie's and fixed. (ForestryMC/Binnie#343)
