### ISSUE TITLE
[Suggestion] TOPAddons integration with StorageDrawers

### ISSUE THREAD

**Issue by utoc** [DrManganese/TOPAddons#4]
Greetings,

I'd like like to offer a humble suggestion for TOPAddons's integration to include listing the blocks/items that are stored in StorageDrawers and the current limit to the inventory being looked at, similar to their own builtin WAILA integration.

Currently blocks from the items inventory are displayed as such: http://imgur.com/63GPaxe

The API is located here: https://github.com/jaquadro/StorageDrawers/tree/1.10/src/com/jaquadro/minecraft/storagedrawers/api

Thanks so much for considering it!

**Comment by DrManganese** [comment]
Hi and thanks for the suggestion.
I believe The One Probe already shows storage drawer contents when sneaking. But it doesn't show the limit so I'll add that for sure.

**Comment by utoc** [comment]
Sorry for not being more clear; TOP does show the contents when sneaking but additionally I would like to see item names, stacks+individual items (if thats not too difficult) and limit.

**Comment by DrManganese** [comment]
Ah I see, will do!

**Comment by DrManganese** [comment]
How about something like this? (By default only when sneaking)
![Preview](http://i.imgur.com/lXSgOm5.gif)

**Comment by utoc** [comment]
Thats perfect! Does the stack limit know to read upgrades?

**Comment by DrManganese** [comment]
Yes it does, just like that waila screenshot it'll show **Stack limit:** Base (xMultiplier)

**Comment by DrManganese** [comment]
Up on curse now! Thanks for the suggestion!
