### ISSUE TITLE
[1.12.2-1.2.0] Crash on startup 

### ISSUE THREAD

**Issue by billybricker** [DrManganese/TOPAddons#40]
As the title says 1.2.0 crashes on startup, reverting to 1.1.3 fixes it. Looks like it's trying to get some classes that don't exist because I don't have Binnie's installed.

https://pastebin.com/iWPiDnn3

**Comment by DrManganese** [comment]
Thanks for the report. Will be fixed asap tomorrow. I've removed the version from curse in the meantime.
