### ISSUE TITLE
Compacting Storage Drawers

### ISSUE THREAD

**Issue by mebert02** [DrManganese/TOPAddons#41]
Compacting Storage Drawers have no information. All of the other Drawers from Storage Drawers work fine. TOP version 1.4.19, TOPAddons version 1.1.3, Storage Drawers version 5.33

**Comment by DrManganese** [comment]
Do you mean this information (not sneaking):
![https://i.imgur.com/X8ZiUIx.png](https://i.imgur.com/X8ZiUIx.png)

or this information (sneaking):
![https://i.imgur.com/zX7rcpX.png](https://i.imgur.com/zX7rcpX.png)

**Comment by DrManganese** [comment]
The extended information shows up on all drawers, including compacting drawers. If you want the *non-sneaking* info to show up you'll have to add `storagedrawers:compdrawers` to the *showContentsWithoutSneaking* config option in The One Probe's config file.
