### ISSUE TITLE
Add text labels to Storage Drawers info panel.

### ISSUE THREAD

**Issue by SirWindfield** [DrManganese/TOPAddons#44]
I have a hard time distinguishing between different ores that I store in those drawers. The icons look way too similar (e.g. Aluminium, Lead, Nickel) are all kind of silverish.

Would you be fine with having the content of the drawer drawn as an icon with the item name right next to it? Meaning that, for example, the 4 item drawer would have 4 rows, each having the item icon displayed and the text right next to the item icon.

Not sure if this change is hard to accomplish as I have no idea how to use the TOP/Storage Drawer API but I might create a PR if this is easy to do.

**Comment by DrManganese** [comment]
By default The One Probe already does this when looking at a drawer while sneaking:
![jAMmH.png](https://s1-cdn.photoland.io/jAMmH.png)

Additionally TOP Addons changes this to add more info:
![jAX4t.png](https://s1-cdn.photoland.io/jAX4t.png)

(This feature requires a probe in hand/helmet/bauble or have the config set to not require a probe for extended.)

**Comment by SirWindfield** [comment]
Strange, because I set the config to not require the probe and enabled extended. Let me check again.

**Comment by DrManganese** [comment]
I forgot about the *extendedInMain* config, when set to true it shows both. I'll fix it asap.

(sorry for the very late response)

**Comment by SirWindfield** [comment]
No problem :smile: Thanks for your help!
