### ISSUE TITLE
Binnie's Extra Trees Mod Support tweaking

### ISSUE THREAD

**Issue by MeinKraft** [DrManganese/TOPAddons#45]
MC: 1.12.2
FORGE: 14.23.2.2624
TOP: 1.12-1.4.19
TOPAddOns: 1.12.2-1.4.0

I planted some Hops from Binnies Extra Trees. Its a 2 block tall flower. When looking at the bottom half TheOneProbe displays correct growth rate. When looking at the top half it always says 0% Growth.

Is this something you can fix or is it a OneProbe problem ?

**Comment by DrManganese** [comment]
I'll have a look.

**Comment by DrManganese** [comment]
Should do it, not something Binnie's or TOP could fix, the `getAge` method doesn't supply a world context.
