### ISSUE TITLE
[1.12] Crash when looking at a Forestry Multi Block Farm

### ISSUE THREAD

**Issue by MasterEnderman** [DrManganese/TOPAddons#46]
Crash Report: https://pastebin.com/ZPKrh60K
Forge: 14.2.23.2634
McJtyLib: 3.0.4
The One Probe: 1.4.21
TOP Addons: 1.4.0 
Forestry: 5.8.0.256

**Comment by DrManganese** [comment]
Seems like I'll have to update to newer dependencies, thanks for the report. New version asap.
