### ISSUE TITLE
[1.12.2] Error permanently

### ISSUE THREAD

**Issue by TheSnowyChickens** [DrManganese/TOPAddons#48]
Hello,
this bug happends with the newest Thermal versions.
It occures at EVERY machine block, like Pulverizer, IE squeezer, AE blocks and and and

![2018-04-28_21 35 00](https://user-images.githubusercontent.com/29357962/39400433-9a2d911e-4b30-11e8-83e7-4f5114a473f2.png)

1.12.2-forge1.12.2-14.23.3.2676
theoneprobe-1.12-1.4.22
topaddons-1.12.2-1.5.0
ThermalFoundation-1.12.2-2.4.1.15-universal
ThermalExpansion-1.12.2-5.4.2.25-universal
ThermalDynamics-1.12.2-2.4.1.9-universal
CoFHCore-1.12.2-4.4.1.12-universal
mcjtylib-1.12-2.6.7

**Comment by DrManganese** [comment]
Thanks for the report, will fix asap.

**Comment by TheSnowyChickens** [comment]
Np, I asked KingLemming also, because I didn't know if its a bug from his side or your side.
He wrote back with following:
------------------------------
"Some classes got refactored internally. TOPAddons will have to update.

Not really a bug on either end, just a consequence of them directly referring to some of my classes and then those classes being moved around."
------------------------------
And so I knew, I am at the right position here. :)

**Comment by ate0ate** [comment]
Very nice, I was just about to report this issue. Are you planning on publishing this fix to curseforge in the near future by any chance?

**Comment by DrManganese** [comment]
I uploaded it a few hours ago, just waiting for approval.

**Comment by ate0ate** [comment]
Wow, you move quickly lol. Thanks for the response.

**Comment by discolight99** [comment]
V1.12.2-1.6.0 has been approved

**Comment by TheSnowyChickens** [comment]
Thx
