### ISSUE TITLE
[Suggestion] Botania Mana Support

### ISSUE THREAD

**Issue by xnerbop** [DrManganese/TOPAddons#5]
I know Botania is made for visual representation but could you make it so the amount of mana in pools, flowers, and spreaders is visual in a number format when holding the wand of the forest. Also if its not too much trouble make a probe version for all the Botania magical helms.

**Comment by DrManganese** [comment]
Thanks for the suggestion, unfortunately I won't be adding any numerical representation of mana. Botania was designed to be GUI-less and numberless and I feel like displaying the internal information would break the balance of mod.

I'm currently working on redoing how the probed helmets work so expect probed botania helmets soon.

**Comment by xnerbop** [comment]
OK thanks anyways.
