### ISSUE TITLE
Crash on Startup - Issue with IC2 Classic?

### ISSUE THREAD

**Issue by NormanNormalington** [DrManganese/TOPAddons#55]
Using Forge 2758, TOP Addons 1.8.0, The One Probe 1.4.23 and IC2 Classic 1.5.3.1 for Minecraft 1.12.2. 
https://gist.github.com/NormanNormalington/0d66f457c3ffa71266fbbf2cab3d9129

**Comment by DrManganese** [comment]
Quick uppercase/lowercase fix, will update this evening.
