### ISSUE TITLE
Roost support

### ISSUE THREAD

**Issue by Pival81** [DrManganese/TOPAddons#58]
it'd be awesome to have progress tooltips for Roost's block, such as the roost breeder and the roost itself.

**Comment by DrManganese** [comment]
Thanks for the suggestion, I'll look into it!

**Comment by Pival81** [comment]
That's just perfect!

**Comment by DrManganese** [comment]
I will try to put out an update tonight. Will comment here again once it's live on curseforge.

**Comment by DrManganese** [comment]
v1.12.2-1.10.0 available on CurseForge now!
