### ISSUE TITLE
ArchitectureCraft

### ISSUE THREAD

**Issue by MeinKraft** [DrManganese/TOPAddons#59]
I know you added ArchitectureCraft support but with version 1.12-3.80 all the blocks show up as Architecture Block instead of with their variant name. Could you add the variant names back please?

ArchitectureCraft 1.12-3.80
TOP AddOns 1.12.2-1.9.2

**Comment by DrManganese** [comment]
I'll have a look!

**Comment by DrManganese** [comment]
Added back the support, I didn't realize someone took over the project.
I saw that the first time you requested support that you preferred the "base block" name to be at the top, like the chisel blocks, so I made that the default.
There is a config option to swap shape name and block name.

**Comment by MeinKraft** [comment]
Thank you.

I believe there are two versions of ArchitectureCraft, an ElytraDev version or something.  But thank you for making the changes
