### ISSUE TITLE
RE: Roost Support

### ISSUE THREAD

**Issue by boosterdev** [DrManganese/TOPAddons#60]
First of all I must say this looks good on a client.

But when on a remote server this does not works at all.

**Comment by DrManganese** [comment]
Do you mean it looks different or that it is not showing the information?

**Comment by boosterdev** [comment]
Its not showing the information, 
![screenshot from 2018-11-28 12-57-18](https://user-images.githubusercontent.com/25176087/49150383-fc215480-f30c-11e8-8867-a062d82c18bb.png)

**Comment by DrManganese** [comment]
I did not notice Roost using client-side localization. Using the actual itemstack now.
Thanks for the report.

**Comment by boosterdev** [comment]
Confirmed as Fixed
