### ISSUE TITLE
ShowTankSetting is ignored.

### ISSUE THREAD

**Issue by flannerby** [DrManganese/TOPAddons#61]
The ShowTankSetting in theoneprobe.cfg is ignored while this mod is installed (always treated as 2). While the mod is installed sneak or probe is required to see tank values, yet not when removed. Even when changing to The One Probe view for tanks, nothing is displayed without sneak or probe.

**Comment by lqg5522** [comment]
Similarly, it would render “showContentsWithoutSneaking” of theoneprobe.cfg ineffective.

**Comment by DrManganese** [comment]
Thanks for reporting this, and sorry for the long wait.
TOPAddons will now respect the `showTankSetting` option when not overriding the TOP tank.

v1.12.2-1.11.0 is on CurseForge with this change now.
