### ISSUE TITLE
[feature request] Mystical Agriculture Seed Tiers

### ISSUE THREAD

**Issue by Slyklaw** [DrManganese/TOPAddons#62]
Mystical Agriculture seeds have Tiers that do not display with TOP. This is especially important with Inferium Seed Tiers so you can know which seeds are which in a large farm. Can that be added?

**Comment by DrManganese** [comment]
Thanks for the suggestion! I added the tier information on seeds and additionally fuel level on preprocessors.

v1.12.2-1.11.0 is on CurseForge now with the changes.
