### ISSUE TITLE
1.12.2 compatablity Storage Drawers Extras

### ISSUE THREAD

**Issue by trestmen** [DrManganese/TOPAddons#63]
Is there anyway to add support for Storage Drawers Extras I know its an older mod but is up to date to 1.12.2.

**Comment by DrManganese** [comment]
Thanks for the suggestion, I will have a look. If there is something specific you would want the probe to show then please let me know.

**Comment by trestmen** [comment]
Cool thank you and just want them to show what normal storage drawers shows lol

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 18, 2019 at 10:28 AM, Mathias de Jong<notifications@github.com> wrote:   
Thanks for the suggestion, I will have a look. If there is something specific you would want the probe to show then please let me know.

**Comment by DrManganese** [comment]
Alright, I'll try make the current implementation more generic then.

**Comment by DrManganese** [comment]
Closing this issue as I'm no longer supporting 1.12 and Storage Drawers Extras is not available yet for 1.16.
