### ISSUE TITLE
Request: Add support for AbyssalCraft

### ISSUE THREAD

**Issue by clonetrooper277** [DrManganese/TOPAddons#65]
It would be nice if TOPAddons could support AbyssalCraft's Potential Energy since just looking at a block and seeing how much energy is stored is better than being forced to use a block's GUI. Some blocks in AbyssalCraft can store energy, but have no GUI and no way of checking how much energy is stored. Thanks!

**Comment by DrManganese** [comment]
AbyssalCraft support was implemented while working on 1.12. When the mod updates to 1.16 I will port the code.
Thanks for the feature request.
