### ISSUE TITLE
Support growth stage for Ender Lilies from Extra Utils 2

### ISSUE THREAD

**Issue by Dilnu** [DrManganese/TOPAddons#66]
It would be nice to be able to see the growth stage on Ender lilies like you can for vanilla crops.

**Comment by discolight99** [comment]
It has been added,
It will be in the next curseforge release.

**Comment by DrManganese** [comment]
Released on CurseForge with version [1.12.2-1.13.0](https://www.curseforge.com/minecraft/mc-mods/top-addons/files/2887479).
