### ISSUE TITLE
AddonStorageDrawers  broken

### ISSUE THREAD

**Issue by samtrion** [DrManganese/TOPAddons#67]
With the last update 1.12.2 of StorageDrawers the addon is broken...

**Comment by DrManganese** [comment]
Could you elaborate on what is broken? Testing it with the latest versions of TOPAddons and Storage Drawers I don't immediately find what is broken.

**Comment by samtrion** [comment]
The taped Drawer is always displayed.

**Comment by DrManganese** [comment]
That is out of my control. The One Probe renders the icon based on the item stack you would get from middle-clicking. StorageDrawers probably changed the pick block functionality.

**Comment by samtrion** [comment]
Damn.. :(
