### ISSUE TITLE
Visual error while installed with LycanitesMobs

### ISSUE THREAD

**Issue by MadRatSRP** [DrManganese/TOPAddons#68]
![2019-11-06_20 53 05](https://user-images.githubusercontent.com/29717217/68327112-c7517c00-00dd-11ea-888a-8cbcf2c4f668.png)
![2019-11-06_21 05 43](https://user-images.githubusercontent.com/29717217/68327114-c7517c00-00dd-11ea-95cd-0b221df1c0a8.png)

**Comment by discolight99** [comment]
What version of Minecraft are you running?

**Comment by discolight99** [comment]
I am able to replicate the issue,
I used version 1.12.2 2.0.1.2 - LycanitesMobs
TopAddons - 1.12.2 1.11.0
The One Probe - 1.12.2 1.4.28
Forge 1.12.2 14.23.5.2847

Thanks for the report.

**Comment by discolight99** [comment]
This fix will be on curseforge today.
If there still is an issue feel free to reopen the ticket.
