### ISSUE TITLE
[COMPAT] Expanded TiCon Support

### ISSUE THREAD

**Issue by squirrelkiller** [DrManganese/TOPAddons#7]
Progress with Seared Furnace,
Drying Racks (if not already a thing as I normally mostly use these early game only)
I haven't tested yet, but I would be surprised if the seared tank showed fluids like the smeltery did.

**Comment by DrManganese** [comment]
Sorry for the late response, been busy. :/
I added progress text to the Drying Racks, but I don't know what to show for the seared furnace. Adding progress for each item being smelted seems a bit overkill. But let me know of I understood you wrong!

Thanks for the feedback!
