### ISSUE TITLE
Hi, I am playing the Dungeons, Dragons, and Space Shuttles Modpack on Curseforge and I am getting this weird error where I can't get any of the tinkers to construct smeltery controllers to work when I click on them. It says "Error: topaddons:tconstruct. Does anyone know how to fix this? #365

### ISSUE THREAD

**Issue by theowspang** [DrManganese/TOPAddons#70]
<img width="1920" alt="2020-02-22 (25)" src="https://user-images.githubusercontent.com/61368565/75115011-a414f300-5620-11ea-86db-c9cdfafa6e71.png">

**Comment by DrManganese** [comment]
Thanks for submitting this issue, I will have a look ASAP.

**Comment by DrManganese** [comment]
It appears that you are looking at an invalid setup. I don't believe it is possible to have a smeltery controller and a tank controller in the same multi-block.

TOP Addons is always showing that error when it is looking at an unformed controller.

**Comment by theowspang** [comment]
You guys are amazing thank you so much!
