### ISSUE TITLE
Startup Crash with Thermal Expansion Dynamos

### ISSUE THREAD

**Issue by sciguyryan** [DrManganese/TOPAddons#86]
Hi.

I ran into this startup crash while loading the mod. It seems to be related to Thermal Expansion's dyanmos.

https://pastebin.com/NBVuPz76

**Comment by DrManganese** [comment]
Thanks for the report, seens like a version mismatch.

**Comment by DrManganese** [comment]
Indeed the build is not compatible with 1.16.4-1.2.0+. I've updated the code and made the mod depend on that minimum version.

**Comment by DrManganese** [comment]
v1.16.5-2.1.1-beta is available on CurseForge now. Please reopen the issue if the crash is still happening for you.
