### ISSUE TITLE
1.16.x-2.1.0 has hard dependency on Industrial Foregoing

### ISSUE THREAD

**Issue by BrisingrAerowing** [DrManganese/TOPAddons#87]
As per title. This causes a crash on startup if IF isn't installed.

**Comment by DrManganese** [comment]
Oops, will fix ASAP.

**Comment by DrManganese** [comment]
Fix will be part of v1.16.5-2.1.1-beta which will be released later today.

Thanks for the report.

**Comment by DrManganese** [comment]
v1.16.5-2.1.1-beta is available on CurseForge now. Please reopen the issue if the crash is still happening for you.
