### ISSUE TITLE
StorageDrawers version update has broken that aspect of TOPAddons

### ISSUE THREAD

**Issue by utoc** [DrManganese/TOPAddons#9]
Seen here: http://i.imgur.com/E9JvJfw.png?1

Commit in question: https://github.com/jaquadro/StorageDrawers/pull/350 but the full changelog is here: https://github.com/jaquadro/StorageDrawers/commits/1.10

Running topaddons-1.10.2-0.8.0, theoneprobe-1.10-1.1.6 and FML 2014

**Comment by DrManganese** [comment]
Thanks for the report, fixing right away!

**Comment by DrManganese** [comment]
The issue is actually your theoneprobe version, I changed some Storage Drawers stuff after McJty added some custom support for them in v1.10-1.2.0. I'll add a required version for future releases!

**Comment by utoc** [comment]
Oh, woops.  Do I need to downgrade TOP?

**Comment by DrManganese** [comment]
Upgrade actually, you have 1.1.6 and latest is 1.2.0

**Comment by utoc** [comment]
Oh.  Wow, big time derp on my part.  Thanks bro.

**Comment by DrManganese** [comment]
No problemo!
