### ISSUE TITLE
[1.16.5] Crash when selecting Tinkers Bronze in the Tinker's Construct Smeltery Controller.

### ISSUE THREAD

**Issue by Gbergz** [DrManganese/TOPAddons#91]
Title^

When Tinkers Bronze is selected in the Smeltery Controller GUI the game crashes. 

**Minecraft:** 1.16.5
**The One Probe:** 3.0.7
**TOP Addons:** 2.1.1-beta
**Tinker's Construct**: 1.16.5-3.0.2.96

**Crash-Report 1**: https://gist.github.com/Gbergz/6d3777e93f6d9af4ac0e51bccb1c6054
**Crash-Report 2**: https://gist.github.com/Gbergz/9c08e4673b2bda3711b13220487cd479

**-** Gbergz

**Comment by DrManganese** [comment]
Thanks for the report. Which block were you looking at when the crashes happened?

**Comment by Gbergz** [comment]
The Smeltery Controller.

**Comment by DrManganese** [comment]
I can't seem to reproduce the error. Does the Smeltery Controller show a fluid gauge when the Bronze is not selected? For me it doesn't expose any tank/fluids.

**Comment by Gbergz** [comment]
Welp, now I can't seem to reproduce the crash either. It was happening every time earlier today. Selecting the Tinkers Bronze fluid inside the Controller w/ multiple fluids would lead to those crashes. Nothing now. How strange.

**Comment by DrManganese** [comment]
I'll add something to catch that exception just in case. Thanks for checking again.

**Comment by Gbergz** [comment]
Recently got a similar crash randomly around my base. 
Not sure exactly what caused it. Using version``topaddons-1.16.5-2.1.2-beta.jar``

**Crash-Report**: https://gist.github.com/Gbergz/e02bcc9612502491ecd7fde7905b60a0

**Comment by DrManganese** [comment]
With the previous fix it should fall back to using water's texture, and I didn't expect that to be null too...
Still can't reproduce, but I will make it double-safe by just falling back to a color this time.

In the meantime you can change the forge.fluidGauge.gaugeRenderFluidTexture config option to `true` so it doesn't try to get the fluid colour at all.

Thanks for reporting.

**Comment by DrManganese** [comment]
Issue should be resolved since v1.16.5-2.1.2-beta. Please reopen if it happens again.
