### ISSUE TITLE
Crash when hovering over Mekanism pipes

### ISSUE THREAD

**Issue by SillyGoose078** [DrManganese/TOPAddons#93]
### Issue Description
Hovering over an Advanced Logistical Transporter from Mekanism immediately crashes the client with the attached error.

### To Reproduce
1. Add an item to an Advanced Logistical Transporter
2. Hover over the Advanced Logistical Transporter

### Crash Report
[crash-2021-04-16_21.14.16-client.txt](https://github.com/DrManganese/TOPAddons/files/6328450/crash-2021-04-16_21.14.16-client.txt)

**Comment by DrManganese** [comment]
Thanks for the report. Seems to be the same error as #91 and will be fixed by PR #92 which will be published to CurseForge soon.
